### ISSUE TITLE
App did not work on Edge's tabs in a group

### ISSUE THREAD

**Issue by the-phuctran** [hereafter/browsers-shortcuts#1]
I have 2 problems when using the app:
firstly, sometime double clicking to close rarely not working on Edge
secondly, when tabs in a group, I cannot double click to close them.

**Comment by hereafter** [comment]
Thanks for reporting, I am investigating these issues. 

For the second issue, i can reproduce easily, it is a new feature added to Edge.

I am not able to reproduce the first issue.
Would you please provide some detailed information on the first case,

1. Edge version, and Window Version.
If possible could you please provide some screenshots or a recording of what happened.

**Comment by the-phuctran** [comment]
I just don't know when it happens to perform a record, double click occasionally delays closing or didn't work without any knowing acts. I will try to catch it when it's come.

**Comment by hereafter** [comment]
An update is posted to Microsoft Store, it will be available soon,
It fixes tabs in a group.

Let me know if this release is better for you to use.

**Comment by the-phuctran** [comment]
The update works perfectly!!! Thank you for your great app.
